VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IInterface"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public Sub PropertyChanged()
End Sub

Public Property Get IInterfaceProperty() As IRibbonUI
End Property

Public Property Let IInterfaceProperty(Value As IRibbonUI)
End Property

public sub IInterfaceFunction()
End sub